require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'clearSaleApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  #pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  target 'clearSaleAppTests' do
    inherit! :complete
    # Pods for testing
  end

  source	'https://dev.azure.com/PublicPackagesCS/Behavior/_git/BehaviorAnalytics.SDK.IOS.Specs'
  pod 'CSBehavior', '3.0.1'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target 'clearSaleApp-tvOS' do
  # Pods for clearSaleApp-tvOS

  target 'clearSaleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
